In [2]:
import numpy as np 
import time


In [3]:
a = np.zeros(4);    
print(f"np.zeros(4): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
a = np.zeros((4,)); 
print(f"np.zeros(4): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
a = np.random.random_sample(4)
print(f"np.random.random_sample(4): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

np.zeros(4): a = [0. 0. 0. 0.], a shape = (4,), a data type = float64
np.zeros(4): a = [0. 0. 0. 0.], a shape = (4,), a data type = float64
np.random.random_sample(4): a = [0.39983227 0.53599678 0.31146735 0.68516922], a shape = (4,), a data type = float64


In [4]:
a = np.arange(4.);
print(f"np.arange(4.): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
a = np.random.rand(4);
print(f"np.random.rand(4): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")


np.arange(4.): a = [0. 1. 2. 3.], a shape = (4,), a data type = float64
np.random.rand(4): a = [0.79430954 0.7072698  0.08898143 0.276091  ], a shape = (4,), a data type = float64


In [5]:
a = np.array([5, 4, 3, 2])
print(f"np.array([5, 4, 3, 2]): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
a = np.array([5., 4, 3, 2])
print(f"np.array([5., 4, 3, 2]): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

np.array([5, 4, 3, 2]): a = [5 4 3 2], a shape = (4,), a data type = int64
np.array([5., 4, 3, 2]): a = [5. 4. 3. 2.], a shape = (4,), a data type = float64


In [6]:
a = np.arange(10)
print(a)
print(a.shape)
print(f"a[2].shape: {a[2].shape} a[2]  = {a[2]}, Accessing an element returns a scalar")

print(f"a[-1] = {a[-1]}")

try:
    c = a[10]
except Exception as e:
    print("The error message you'll see is:")
    print(e)


[0 1 2 3 4 5 6 7 8 9]
(10,)
a[2].shape: () a[2]  = 2, Accessing an element returns a scalar
a[-1] = 9
The error message you'll see is:
index 10 is out of bounds for axis 0 with size 10


In [16]:
a = np.arange(10)
print(f"a = {a}")


# access to 5 consecutive elements (start:stop:step)
c = a[2:7:1]; print(f"a[2:7:1] = {c}")

# access to 3 elements separated by two
c = a[2:7:2]; print(f"a[2:7:2] = {c}")

# access all elements index 3 above
c = a[3:]; print(f"a[3:] = {c}")

# access all elements below index 3 
c = a[:3]; print(f"a[:3] = {c}")

# access all elements
c= a[:]; print(f"a[:] = {c}")

a = [0 1 2 3 4 5 6 7 8 9]
a[2:7:1] = [2 3 4 5 6]
a[2:7:2] = [2 4 6]
a[3:] = [3 4 5 6 7 8 9]
a[:3] = [0 1 2]
a[:] = [0 1 2 3 4 5 6 7 8 9]


Single vector operations:

In [21]:
a = np.array([1,2,3,4]); print(f"a = {a}")

# negate values of a
b = -a; print(f"-a = {b}")

#sum all elements of a, return a scalar
b = np.sum(a); print(f"b = np.sum(a):   {b}")

# return de mean of a
b = np.mean(a); print(f"b = np.mean(a) :         {b}")

# square of vector a
b = a**2; print(f"b = a**2:     {b}")

a = [1 2 3 4]
-a = [-1 -2 -3 -4]
b = np.sum(a):   10
b = np.mean(a) :         2.5
b = a**2:     [ 1  4  9 16]


vector wise elements

In [22]:
a = np.array([1,2,3,4])
b = np.array([-1,-2,-3,-4])

print(f"Binary operators work elements wise: {a+b}")

Binary operators work elements wise: [0 0 0 0]


try a mismatched vector operation

In [23]:
c = np.array([1, 2])

try: 
    d = a + c
except Exception as e:
    print("The error message you'll see is: ")
    print(e)

The error message you'll see is: 
operands could not be broadcast together with shapes (4,) (2,) 


Scalar vector operations:

In [24]:
a = np.array([1, 2, 3, 4])
# multyply by a scalar
b = 5*a
print(f"b = 5*a :        {b}")

b = 5*a :        [ 5 10 15 20]


vector vecto dos product

In [26]:
def my_dot(a,b):
    x = 0

    for i in range(a.shape[0]):
        x = x + a[i]*b[i]
    
    return x

In [27]:
a = np.array([1,2,3,4])
b = np.array([-1,4,3,2])

print(f"my_dot(a, b) = {my_dot(a,b)}")

my_dot(a, b) = 24


In [29]:
a = np.array([1,2,3,4])
b = np.array([-1,4,3,2])

c = np.dot(a,b)
print(f"Numpy 1-D np.dot(a, b) = {c}, np.dot(a, b).shape = {c.shape}")
c = np.dot(b,a)
print(f"Numpy 1-D np.dot(b, a) = {c}, np.dot(b, a).shape = {c.shape}")

Numpy 1-D np.dot(a, b) = 24, np.dot(a, b).shape = ()
Numpy 1-D np.dot(b, a) = 24, np.dot(b, a).shape = ()


In [33]:
np.random.seed(1)

a = np.random.rand(10000000)
b = np.random.rand(10000000)

tic = time.time()
c = np.dot(a,b)
toc = time.time()

print(f" np.dot(a,b) = {c:.4f}")
print(f"time version duration: {1000*(toc-tic):.4f} ms")

tic = time.time()
c = my_dot(a,b)
toc = time.time()

print(f" my_dot(a,b) = {c:.4f}")
print(f"time version duration: {1000*(toc-tic):.4f} ms")

del(a)
del(b)

 np.dot(a,b) = 2501072.5817
time version duration: 9.6931 ms
 my_dot(a,b) = 2501072.5817
time version duration: 3829.7172 ms


In [35]:
X = np.array([[1],[2],[3],[4]])
w = np.array([2])
c = np.dot(X[1],w)

print(c)

print(f"X[1] has shape {X[1].shape}")
print(f"w has shape {w.shape}")
print(f"c has shape {c.shape}")

4
X[1] has shape (1,)
w has shape (1,)
c has shape ()


Matrix creation 

In [39]:
a = np.zeros((1,5))
print(f"a shape = {a.shape}, a = {a}")
a = np.zeros((2,1))
print(f"a shape = {a.shape}, a = {a}")
a = np.random.random_sample(1)
print(f"a shape = {a.shape}, a = {a}")

a shape = (1, 5), a = [[0. 0. 0. 0. 0.]]
a shape = (2, 1), a = [[0.]
 [0.]]
a shape = (1,), a = [0.04997798]


In [41]:
a = np.array([[5],[4],[3]]); print(f"a shape = {a.shape}, np.array: a = {a}")
a = np.array([[5],
              [4],
              [3]]); 
print(f"a shape = {a.shape}, np.array: a = {a}")

a shape = (3, 1), np.array: a = [[5]
 [4]
 [3]]
a shape = (3, 1), np.array: a = [[5]
 [4]
 [3]]


In [49]:
a = np.arange(20).reshape(-1,2)
print(f"a.shape : {a.shape}, \na = {a}")

print(f"\na a[2,0] = {a[2,0].shape}, a[2,0]={a[2,0]}")

a.shape : (10, 2), 
a = [[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]

a a[2,0] = (), a[2,0]=4


In [56]:
a =  np.arange(20).reshape(-1,10)
print(f"a = {a}")

# acces to consecutive elements

print("a[0,2:7:1]", a[0,2:7:1], "a[0,2:7:1].shape", a[0,2:7:1].shape, "a 1-D array")

#access 5 consecutive elements (start:stop:step) in two rows

print("a[:,2:7:1]", a[:,2:7:1], "a[:,2:7:1].shape", a[:,2:7:1].shape, "a 2-D array")

#access all elements
print("a[:,:]", a[:,:], "a[:,:].shape", a[:,:].shape, "a 2-D array")

# access all elements   in one row 
print("a[1,:]", a[1,:], "a[1,:].shape", a[1,:].shape, "a 2-D array")

# same as 
print("a[1]", a[1], "a[1].shape", a[1].shape, "a 2-D array")

a = [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
a[0,2:7:1] [2 3 4 5 6] a[0,2:7:1].shape (5,) a 1-D array
a[:,2:7:1] [[ 2  3  4  5  6]
 [12 13 14 15 16]] a[:,2:7:1].shape (2, 5) a 2-D array
a[:,:] [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]] a[:,:].shape (2, 10) a 2-D array
a[1,:] [10 11 12 13 14 15 16 17 18 19] a[1,:].shape (10,) a 2-D array
a[1] [10 11 12 13 14 15 16 17 18 19] a[1].shape (10,) a 2-D array
